resp <- structure(list(url = "https://www.givebriq.com/v0/organizations/your-organization/users",
    status_code = 200L, headers = structure(list(date = "Tue, 02 Apr 2019 23:09:15 GMT",
        `content-type` = "application/json; charset=utf-8", `transfer-encoding` = "chunked",
        connection = "keep-alive", `x-dns-prefetch-control` = "off",
        `x-frame-options` = "SAMEORIGIN", `strict-transport-security` = "max-age=15552000; includeSubDomains",
        `x-download-options` = "noopen", `x-content-type-options` = "nosniff",
        `x-xss-protection` = "1; mode=block", `content-language` = "en",
        `set-cookie` = "REDACTED", `x-powered-by` = "Express",
        link = "", etag = "test",
        vary = "Accept-Encoding", `content-encoding` = "gzip",
        via = "1.1 vegur", `expect-ct` = "max-age=604800, report-uri=null",
        server = "null", `cf-ray` = "null"), class = c("insensitive",
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1",
        headers = structure(list(date = "Tue, 02 Apr 2019 23:09:15 GMT",
            `content-type` = "application/json; charset=utf-8",
            `transfer-encoding` = "chunked", connection = "keep-alive",
            `x-dns-prefetch-control` = "off", `x-frame-options` = "SAMEORIGIN",
            `strict-transport-security` = "max-age=15552000; includeSubDomains",
            `x-download-options` = "noopen", `x-content-type-options` = "nosniff",
            `x-xss-protection` = "1; mode=block", `content-language` = "en",
            `set-cookie` = "REDACTED", `x-powered-by` = "Express",
            link = "", etag = "null",
            vary = "Accept-Encoding", `content-encoding` = "gzip",
            via = "1.1 vegur", `expect-ct` = "max-age=604800, report-uri=null",
            server = "cloudflare", `cf-ray` = "4c16782a8f41cab2-YYZ"), class = c("insensitive",
        "list")))), cookies = structure(list(domain = c("#HttpOnly_.givebriq.com",
    "www.givebriq.com"), flag = c(TRUE, FALSE), path = c("/",
    "/"), secure = c(FALSE, TRUE), expiration = structure(c(1,
    1), class = c("POSIXct", "POSIXt")), name = c("null",
    "null"), value = c("REDACTED", "REDACTED")), row.names = c(NA,
    -2L), class = "data.frame"), content = charToRaw("[{\"id\":\"ddfdb19c-e3ad-4300-8ed7-d79e10b9f124\",\"username\":\"alice@your-organization.com\",\"displayName\":\"Alice\",\"email\":\"alice@your-organization.com\",\"externalRef\":null,\"firstName\":null,\"lastName\":null,\"inactiveBalance\":6,\"activeBalance\":1,\"role\":\"user\",\"created_at\":\"2018-10-17T09:55:16.829Z\",\"image\":null}]"),
    date = structure(1554246555, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.6e-05,
    connect = 3.8e-05, pretransfer = 0.00014, starttransfer = 0.488018,
    total = 0.679931)), class = "response")
